# Generated by Django 2.2.3 on 2019-08-31 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20190831_2137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='answer',
            name='corr_answer',
            field=models.CharField(choices=[('1', 'Option 1'), ('1', 'Option 2'), ('1', 'Option 3'), ('1', 'Option 4')], max_length=1),
        ),
    ]
