# Generated by Django 2.2.3 on 2019-08-31 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20190831_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='corr_answer',
            field=models.CharField(choices=[('1', 'option1'), ('2', 'option2'), ('3', 'option3'), ('4', 'option4')], max_length=1),
        ),
    ]
