# Generated by Django 2.2.3 on 2019-09-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20190831_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='instructions',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_lim',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
