# Generated by Django 2.2.3 on 2019-09-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0005_auto_20190901_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='time_lim',
            field=models.CharField(max_length=11),
        ),
    ]
