# Generated by Django 2.1.5 on 2019-04-03 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name of Student')),
                ('reg_no', models.IntegerField(verbose_name='Registration Number')),
                ('pref_1', models.CharField(max_length=200, verbose_name='Preference 1')),
                ('pref_2', models.CharField(max_length=200, verbose_name='Preference 2')),
                ('pref_3', models.CharField(max_length=200, verbose_name='Preference 3')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Name of Student')),
                ('reg_no', models.IntegerField(verbose_name='Registration Number')),
                ('branch', models.CharField(max_length=200, verbose_name='Branch')),
                ('cpi', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='CPI')),
                ('email', models.EmailField(max_length=100, verbose_name='Email of Student')),
                ('phone_no', models.IntegerField(verbose_name='Phone Number')),
                ('is_lead', models.BooleanField(default=False, verbose_name='Is Leader or not')),
                ('is_avail', models.BooleanField(default=True, verbose_name='Is Available')),
            ],
        ),
    ]
