# Generated by Django 2.1.5 on 2019-04-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_allot', '0002_auto_20190403_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$6FXCGhmWMfyN$IkrCaKJjNd3t50aB+Eq/cnGOyDpfY4/DNi28Hdv+qIE=', max_length=500, verbose_name='Hashed Password'),
        ),
    ]
