# Generated by Django 2.1.5 on 2019-04-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_allot', '0003_student_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='pref_allotted',
            field=models.CharField(default='0', max_length=200, verbose_name='Allotted Professor'),
        ),
        migrations.AddField(
            model_name='student',
            name='grp_no',
            field=models.IntegerField(default=0, verbose_name='Group No'),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$120000$CLE9e1wVwJOw$7bxEM0vzNr3CP3FS48U79vPqNQ4eE+U+uwSbxm3zFHc=', max_length=500, verbose_name='Hashed Password'),
        ),
    ]
