# Generated by Django 2.1.5 on 2019-04-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_allot', '0004_auto_20190404_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(default='0', max_length=500, verbose_name='Hashed Password'),
        ),
    ]
