# Generated by Django 2.1.5 on 2019-04-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_allot', '0005_auto_20190404_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='accepted_by',
            field=models.CharField(default='0', max_length=200, verbose_name='Invite Acceptor'),
        ),
        migrations.AddField(
            model_name='student',
            name='invited_by',
            field=models.CharField(default='0', max_length=200, verbose_name='Invited by'),
        ),
    ]
