# Generated by Django 2.1.5 on 2019-04-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_allot', '0006_auto_20190404_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='invited',
            field=models.CharField(default='0', max_length=200, verbose_name='Invitee'),
        ),
    ]
