# Generated by Django 2.1.5 on 2019-04-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_allot', '0007_leader_invited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leader',
            name='accepted_by',
            field=models.CharField(default='0,', max_length=200, verbose_name='Invite Acceptor'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='invited',
            field=models.CharField(default='0,', max_length=200, verbose_name='Invitee'),
        ),
        migrations.AlterField(
            model_name='student',
            name='invited_by',
            field=models.CharField(default='0,', max_length=200, verbose_name='Invited by'),
        ),
    ]
