# Generated by Django 2.1.5 on 2019-04-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_allot', '0008_auto_20190404_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='leader',
            name='has_filled_pref',
            field=models.BooleanField(default=False, verbose_name='Has filled preferences?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_avail',
            field=models.BooleanField(default=True, verbose_name='Is Available?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='is_lead',
            field=models.BooleanField(default=False, verbose_name='Is Leader?'),
        ),
    ]
