# Generated by Django 2.1.5 on 2019-04-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_allot', '0009_auto_20190406_0103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='phone_no',
        ),
        migrations.AddField(
            model_name='leader',
            name='email',
            field=models.EmailField(default='0', max_length=100, verbose_name='Email of Leader'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='password',
            field=models.CharField(default='0', max_length=500, verbose_name='Hashed Password'),
        ),
    ]
