# Generated by Django 2.1.5 on 2019-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Admin')),
                ('user_name', models.CharField(max_length=50, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
            ],
        ),
    ]
