# Generated by Django 2.1.5 on 2019-03-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of Professor')),
                ('dept', models.CharField(max_length=200, verbose_name='Department')),
                ('aoi', models.CharField(max_length=1000, verbose_name='Area of Interest')),
                ('email', models.EmailField(max_length=100, verbose_name='Email of Professor')),
                ('ph_no', models.IntegerField(verbose_name='Phone Number')),
                ('nog', models.IntegerField(verbose_name='No of Groups')),
            ],
        ),
    ]
