# Generated by Django 2.1.5 on 2019-04-06 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prof_add', '0003_auto_20190406_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='ph_no',
        ),
    ]
