# Generated by Django 2.1.5 on 2019-04-06 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_add', '0004_remove_professor_ph_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='is_free',
            field=models.BooleanField(default=True, verbose_name='Is free'),
        ),
    ]
