# Generated by Django 2.1.5 on 2019-04-05 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, verbose_name='Username')),
                ('password', models.CharField(max_length=500, verbose_name='Hashed Password')),
                ('is_stu_pass_set', models.BooleanField(default=False, verbose_name='Is student password set')),
                ('is_mentor_assigned', models.BooleanField(default=False, verbose_name='Is mentor assigned')),
            ],
        ),
    ]
