# Generated by Django 2.1.5 on 2019-04-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='is_lead_allotted',
            field=models.BooleanField(default=False, verbose_name='Are leaders allotted'),
        ),
    ]
