# Generated by Django 2.1.5 on 2019-04-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_administrator_is_lead_allotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrator',
            name='round_1',
            field=models.BooleanField(default=False, verbose_name='Round 1 allotment done'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='round_2',
            field=models.BooleanField(default=False, verbose_name='Round 2 allotment done'),
        ),
        migrations.AddField(
            model_name='administrator',
            name='round_3',
            field=models.BooleanField(default=False, verbose_name='Round 3 allotment done'),
        ),
    ]
